# generated by datamodel-codegen:
#   filename:  dataset_config.yaml
#   timestamp: 2022-11-11T15:25:52+00:00

from __future__ import annotations

from pydantic import BaseModel


class Features(BaseModel):
    case_id: str
    activity: str
    time: str


class Settings(BaseModel):
    name: str
    path: str
    features: Features
